# Generated by Django 4.0.3 on 2022-03-29 02:18

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelnumber', models.CharField(max_length=100)),
                ('jumplevel', models.CharField(max_length=100)),
                ('minimumearning', models.IntegerField()),
                ('salecomissionrate', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('Defaultregistrationlevel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyType', models.CharField(max_length=100)),
                ('SymbolRight', models.CharField(blank=True, max_length=100)),
                ('SymbolLeft', models.CharField(blank=True, max_length=100, null=True)),
                ('IsDefault', models.BooleanField(default=False)),
                ('Status', models.CharField(choices=[('0', 'Enable'), ('1', 'Disable')], default='1', max_length=20)),
                ('Code', models.CharField(max_length=100)),
                ('Value', models.IntegerField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MailType', models.CharField(choices=[('SMTP', 'SMTP'), ('PHP Mailer', 'PHP Mailer')], default='SMTP', max_length=20)),
                ('FromEmail', models.EmailField(max_length=254)),
                ('FromName', models.CharField(max_length=100)),
                ('SMTPHostname', models.CharField(max_length=200)),
                ('SMTPUsername', models.CharField(max_length=200)),
                ('SMTPPassword', models.CharField(max_length=200)),
                ('SMTPPort', models.PositiveIntegerField()),
                ('SMTPCrypto', models.CharField(choices=[('SMTP', 'SMTP'), ('PHP Mailer', 'PHP Mailer')], default='None', max_length=20)),
                ('UnsubscribedPageTitle', models.CharField(max_length=200)),
                ('UnsubscribedPageMessage', models.TextField(max_length=500)),
                ('Testing', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleRecaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitekey', models.CharField(max_length=300)),
                ('secretkey', models.CharField(max_length=300)),
                ('adminlogin', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('affilatelogin', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('affilateregister', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('clientregister', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('clientlogin', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flag', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('Name', models.CharField(max_length=200)),
                ('TranslationMissingAll', models.CharField(max_length=200)),
                ('IsDefault', models.BooleanField(default=False)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(max_length=100)),
                ('frontsitemaintenanceMode', models.CharField(choices=[('0', 'Enable'), ('1', 'Disable')], default='1', max_length=20)),
                ('storemaintenanceMode', models.CharField(choices=[('0', 'Enable'), ('1', 'Disable')], default='1', max_length=20)),
                ('Registrationform', models.CharField(choices=[('EnableAffiliate / VendorRegistration', 'EnableAffiliate / VendorRegistration'), ('DisableAffiliate / VendorRegistration', 'DisableAffiliate / VendorRegistration'), ('Disable Affiliate Registration', 'Disable Affiliate Registration'), ('Disable Vendor Registration', 'Disable Vendor Registration')], default='1', max_length=37)),
                ('Approvalforregistration', models.CharField(choices=[('EnableAffiliate / VendorRegistration', 'EnableAffiliate / VendorRegistration'), ('DisableAffiliate / VendorRegistration', 'DisableAffiliate / VendorRegistration'), ('Disable Affiliate Registration', 'Disable Affiliate Registration'), ('Disable Vendor Registration', 'Disable Vendor Registration')], default='1', max_length=37)),
                ('notificationemail', models.EmailField(max_length=254)),
                ('SessionTimeoutTiming', models.DateTimeField()),
                ('UserSessionTimeoutTiming', models.DateTimeField()),
                ('FooterText', models.CharField(max_length=200)),
                ('timezone', models.DateTimeField(default=datetime.datetime(2022, 3, 29, 2, 18, 31, 36672, tzinfo=utc))),
                ('FrontLanguageDropdown', models.CharField(choices=[('0', 'Enable'), ('1', 'Disable')], default='1', max_length=20)),
                ('hidecurrencyfrom', models.BooleanField(default=False)),
                ('userdashboard', models.BooleanField(default=False)),
                ('adminsidelogo', models.FileField(upload_to='adminsidelogo/')),
                ('customlogosize', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('frontsidelogo', models.FileField(upload_to='frontsidelogo/')),
                ('frontcustomlogosize', models.CharField(choices=[('Enable', 'Enaable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('websitefavicon', models.FileField(upload_to='favicon/')),
                ('description', models.TextField(max_length=100)),
                ('keywords', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('googleanaliticsforsitepage', models.TextField(max_length=200)),
                ('FaceboookPixelCode', models.TextField(max_length=200)),
                ('FacebookChatPluginScript', models.TextField(max_length=200)),
                ('adminside', models.BooleanField(default=False)),
                ('affiliateside', models.BooleanField(default=False)),
                ('storeside', models.BooleanField(default=False)),
                ('frontside', models.BooleanField(default=False)),
                ('globalScript', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermsandCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=200)),
                ('pagecontent', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCokkies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affilateTracking', models.CharField(choices=[('Select', 'Select'), ('Use Cookies', 'Use Cookies'), ('Use Local Storaqge', 'Use Local Storaqge'), ('Use Cookies & Use Local Storaqge', 'Use Cookies & Use Local Storaqge')], default='Select', max_length=32)),
                ('BlockClikAcrossBrowsers', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topaffilate', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
            ],
        ),
    ]
