# Generated by Django 4.0.3 on 2022-03-29 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usefulllinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='Flag',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 2, 51, 57, 236843, tzinfo=utc)),
        ),
    ]
