# Generated by Django 4.0.3 on 2022-03-29 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usefulllinks', '0002_alter_language_flag_alter_sitesetting_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 2, 52, 56, 452137, tzinfo=utc)),
        ),
    ]
