# Generated by Django 4.0.3 on 2022-03-27 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cstatus', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdstatus', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20)),
                ('vminimumdeposit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorMarketTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20)),
                ('clcikstatus', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20)),
                ('noofclick', models.IntegerField()),
                ('amountperclick', models.FloatField()),
                ('commissiontype', models.CharField(choices=[('Select Product Commission Type', 'Select Product Commission Type'), ('Percentage(%)', 'Percentage(%)'), ('Fixed', 'Fixed ')], default='Enable', max_length=30)),
                ('clikcallow', models.CharField(choices=[('Allow Single Click', 'Allow Single Click'), ('Allow Multi Click', 'Allow Multi Click')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnp', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
                ('vnc', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
                ('vns', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
                ('veo', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
                ('vac', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
                ('vcc', models.CharField(choices=[('No need admin aprroval', 'No need admin aprroval'), ('need admin aprroval', 'need admin aprroval')], max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Vendorstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vstatus', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20)),
                ('vclickcommission', models.IntegerField()),
                ('vclickrupees', models.FloatField()),
                ('vsalerupees', models.FloatField()),
                ('vsalecommission', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionssaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('PaymentMethod', models.CharField(max_length=200)),
                ('Total', models.BigIntegerField()),
                ('tStatus', models.CharField(max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
