# Generated by Django 4.0.3 on 2022-03-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyetemOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('total', models.PositiveIntegerField()),
                ('country', models.GenericIPAddressField()),
                ('store', models.ImageField(upload_to='system_store')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Processed', 'Processed')], max_length=100)),
                ('commission', models.CharField(max_length=200)),
                ('systemorderdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_created=True)),
                ('clickid', models.PositiveIntegerField()),
                ('website', models.CharField(max_length=300)),
                ('ip', models.GenericIPAddressField()),
                ('ClickType', models.CharField(max_length=400)),
                ('CustomData', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='walletreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletdate', models.DateTimeField(auto_created=True)),
                ('Commission', models.BigIntegerField()),
                ('From', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('OrderTotal', models.CharField(max_length=100)),
                ('PaymentMethod', models.CharField(max_length=200)),
                ('Comment', models.CharField(max_length=100)),
                ('walletstatus', models.CharField(choices=[('InWallet', 'InWallet'), ('Onhold', 'Onhold'), ('Accept', 'Accept')], max_length=200)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affilatename', models.CharField(max_length=200)),
                ('country', models.ImageField(upload_to='countryreportsystem')),
                ('clickcount', models.IntegerField()),
                ('clickcommission', models.BigIntegerField()),
                ('salecount', models.IntegerField()),
                ('salecommission', models.BigIntegerField()),
                ('cpa', models.CharField(max_length=200)),
                ('totalincome', models.BigIntegerField()),
                ('totalcommission', models.BigIntegerField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
