# Generated by Django 4.0.3 on 2022-03-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syetemorders',
            options={'verbose_name_plural': 'System Orders'},
        ),
        migrations.AlterModelOptions(
            name='systemlogs',
            options={'verbose_name_plural': 'System Logs'},
        ),
        migrations.AlterModelOptions(
            name='systemreport',
            options={'verbose_name_plural': 'System Report'},
        ),
        migrations.AlterModelOptions(
            name='walletreport',
            options={'verbose_name_plural': 'Wallet Report'},
        ),
    ]
