# Generated by Django 4.0.3 on 2022-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlmstatus', models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled'), ('Disable only for selected users', 'Disable only for selected users')], max_length=200)),
                ('ScriptStoreOfflinePaymentMethodReferSaleCommission', models.CharField(choices=[('On Hold', 'On Hold'), ('In Wallet', 'In Wallet')], max_length=200)),
                ('ExternalStoreOfflinePaymentMethodReferSaleCommission', models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled'), ('Disable only for selected users', 'Disable only for selected users')], max_length=200)),
                ('Actionrefer', models.CharField(choices=[('On Hold', 'On Hold'), ('In Wallet', 'In Wallet')], max_length=200)),
                ('showsponser', models.CharField(choices=[('Show Admin As Sponser', 'Show Admin As Sponser'), ('Not Show', 'Not Show'), ('Real Sponser', 'Real Sponser')], max_length=200)),
                ('SponserName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Referlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlmcpr', models.PositiveIntegerField()),
                ('mlmcps', models.PositiveIntegerField()),
                ('mlmcpc', models.PositiveIntegerField()),
                ('mlmcpa', models.PositiveIntegerField()),
            ],
        ),
    ]
